source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify the gem's dependencies in active_billing.gemspec.
gemspec

gem "puma"
gem "pg"
gem "sprockets-rails"

# Jbuilder is used by JSON views generated by `rails g scaffold_controller --api`.
gem "jbuilder"

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "pry"
  gem "rubocop", require: false
end
